image_file_json_valid = r"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAApSURBVChTjcixDQAgAASh339pHQAvsaBh284nohCFKEQhClGIQhTi6QI0vWOd76yXdAAAAABJRU5ErkJggg=="
image_file_json_invalid = r"some_data"
image_file_json_invalid_file_format = r"data:image/pdf;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAApSURBVChTjcixDQAgAASh339pHQAvsaBh284nohCFKEQhClGIQhTi6QI0vWOd76yXdAAAAABJRU5ErkJggg=="
image_file_json_invalid_file_type = r"data:text/plain;base64,SGVsbG8sIHdvcmxkIQ=="
