default:
  # Secrets
  SECRET_KEY: "very-secret-key"
  PASSWORD_MIN_LENGTH: 8 # set to 0 to ignore the character length requirement
  PASSWORD_MAX_LENGTH: 32 # set to 0 to ignore the character length requirement

  # Base configs
  ASYNCIO_LOOP: "asyncio"  # asyncio (for win) or uvloop (for linux)

  # Adapters
  REDIS_URL: "redis://localhost:6380"
  REDIS_MAX_CONNECTIONS: 20
  DATABASE_URL: "postgresql+asyncpg://books_user:books_password@127.0.0.1:5433/books_db"

  # Secrets
  TOKEN_EXPIRATION_MINUTES: 60

  # Application settings
  AUTH_USERNAME_MIN_LENGTH: 3
  BOOK_TITLE_MIN_LENGTH: 1
  BOOK_TITLE_MAX_LENGTH: 255
  BOOK_MIN_PUBLISHED_YEAR: 1500
  BOOK_MAX_PUBLISHED_YEAR: 2025
  AUTHOR_NAME_MIN_LENGTH: 1
  AUTHOR_NAME_MAX_LENGTH: 150
  AUTHOR_MIN_AUTHOR_AGE: 7  # years
  COMMENT_TEXT_MAX_LENGTH: 4096
  PAGINATION_DEFAULT_LIMIT: 10
  PAGINATION_MAX_LIMIT: 100

  # Media
  MEDIA_URL: "/media"
  MEDIA_DIR: "media"

dev:
  # Dev Adapters
  REDIS_URL: "redis://localhost:6380"
  REDIS_MAX_CONNECTIONS: 20
  DATABASE_URL: "postgresql+asyncpg://books_user:books_password@127.0.0.1:5433/books_db"

test:
  # Test Adapters
  REDIS_URL: "redis://localhost:6381"
  REDIS_MAX_CONNECTIONS: 20
  DATABASE_URL: "postgresql+asyncpg://books_user:books_password@127.0.0.1:5434/books_db_test"
